name: CI for FastAPI Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend logic tests
        run: pytest backend_tests/
        env:
          PYTHONPATH: ${{ github.workspace }}

 # Docker Build step
      - name: Build Docker image
        run: docker build -t my-fastapi-app .

      # Optional: Run container to do a basic smoke test
      - name: Test Docker container runs
        run: |
          docker run --rm -d -p 8000:8000 --name test_container my-fastapi-app
          sleep 5
          curl -f http://localhost:8000/ || exit 1
          docker stop test_container